In [8]:
# Import required libraries
import os
import pandas as pd
from pathlib import Path
import hvplot.pandas
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [9]:
# Import required Data,including Increase and Decrease
DTE ='min'
type = 'etfs'
date = '10-11-2022'
increase = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Increase/{type}-increase-change-in-open-interest-{date}.csv'))
decrease = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Decrease/{type}-decrease-change-in-open-interest-{date}.csv'))

#show dataframe

display(increase.head())
display(decrease.head())

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,ARKK,36.47,Call,38.0,2022-10-14,3.0,0.41,0.43,0.44,0.43,789.0,32136.0,"+31,014",84.52%,12:07 ET
1,IWM,169.10,Put,160.0,2022-11-18,38.0,4.17,4.18,4.19,4.13,9980.0,101216.0,"+22,313",36.36%,12:14 ET
2,SPY,361.25,Put,330.0,2022-12-16,66.0,7.57,7.59,7.60,7.50,1298.0,66281.0,"+19,987",32.78%,12:12 ET
3,SPY,361.25,Put,342.0,2022-11-18,38.0,7.06,7.07,7.08,6.83,2797.0,27992.0,"+17,936",31.96%,12:14 ET
4,SPY,361.25,Call,385.0,2022-10-21,10.0,0.69,0.70,0.70,0.70,2114.0,42233.0,"+15,877",29.47%,12:13 ET

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,FXI,25.13,Put,25.0,2022-10-21,10.0,0.65,0.67,0.68,0.64,2605.0,6140.0,"-24,119",40.47%,11:54 ET
1,SPY,361.25,Put,360.0,2022-11-18,38.0,13.29,13.31,13.33,12.99,3491.0,87777.0,"-18,081",29.11%,12:15 ET
2,SPY,361.25,Put,345.0,2022-11-18,38.0,7.82,7.84,7.85,7.80,1799.0,73958.0,"-17,959",31.34%,12:12 ET
3,HYG,71.88,Put,70.0,2022-10-21,10.0,0.38,0.40,0.41,0.40,7743.0,270393.0,"-17,546",21.95%,12:06 ET
4,QQQ,266.15,Put,270.0,2022-10-21,10.0,9.46,9.48,9.50,9.50,1947.0,60157.0,"-13,195",38.14%,12:06 ET

In [10]:
# check Missing Data

display(increase.isnull().sum())
display(increase.isnull().sum())

Symbol      0
Price       1
Type        1
Strike      1
Exp Date    1
DTE         1
Bid         1
Midpoint    1
Ask         1
Last        1
Volume      1
Open Int    1
OI Chg      1
IV          1
Time        1
dtype: int64

Symbol      0
Price       1
Type        1
Strike      1
Exp Date    1
DTE         1
Bid         1
Midpoint    1
Ask         1
Last        1
Volume      1
Open Int    1
OI Chg      1
IV          1
Time        1
dtype: int64

In [11]:
# Handle Missing Data

increase = increase.dropna()
decrease = decrease.dropna()

In [20]:
#Select the data only equal to minimun DTE (closest to expired).

if DTE == 'min':
    increase_min_DTE = increase[increase['DTE'] == increase['DTE'].min()]
    decrease_min_DTE = decrease[decrease['DTE'] == decrease['DTE'].min()]
else:
    increase_min_DTE = increase[increase['DTE'] <= DTE]
    decrease_min_DTE = decrease[decrease['DTE'] <= DTE]


# show dataframe
display(increase_min_DTE)
display(decrease_min_DTE)

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
14,SPY,361.25,Call,365.0,2022-10-12,1.0,0.93,0.94,0.94,1.00,30958.0,14835.0,"+11,238",36.71%,12:15 ET
15,SPY,361.25,Call,362.0,2022-10-12,1.0,1.87,1.88,1.88,1.98,36489.0,13518.0,"+11,238",37.31%,12:15 ET
17,SPY,361.25,Put,350.0,2022-10-12,1.0,0.26,0.27,0.27,0.20,31136.0,22920.0,"+10,889",38.18%,12:14 ET
25,QQQ,266.15,Call,270.0,2022-10-12,1.0,0.57,0.58,0.58,0.58,11832.0,10743.0,"+8,650",40.74%,12:09 ET
29,QQQ,266.15,Put,255.0,2022-10-12,1.0,0.13,0.14,0.14,0.13,5868.0,9051.0,"+7,471",44.56%,12:06 ET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,IWM,169.10,Call,168.0,2022-10-12,1.0,1.68,1.69,1.70,1.78,1886.0,836.0,+343,45.58%,12:15 ET
414,QQQ,266.15,Put,268.0,2022-10-12,1.0,4.30,4.31,4.33,4.18,855.0,2602.0,+326,44.30%,12:09 ET
441,QQQ,266.15,Call,262.0,2022-10-12,1.0,3.96,3.99,4.02,4.04,3553.0,363.0,+249,40.79%,12:09 ET
484,IWM,169.10,Put,163.0,2022-10-12,1.0,0.12,0.13,0.13,0.11,601.0,1059.0,+181,41.83%,12:15 ET
518,IWM,169.10,Call,172.0,2022-10-12,1.0,0.29,0.30,0.31,0.27,1395.0,778.0,+118,42.07%,12:11 ET

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
12,IWM,169.10,Put,164.0,2022-10-12,1.0,0.20,0.21,0.21,0.19,858.0,7026.0,"-3,354",40.61%,12:15 ET
14,QQQ,266.15,Put,270.0,2022-10-12,1.0,5.83,5.86,5.88,5.70,3768.0,5254.0,"-2,880",45.35%,12:08 ET
24,SPY,361.25,Put,362.0,2022-10-12,1.0,3.94,3.96,3.97,3.56,2507.0,7649.0,"-1,535",36.63%,12:14 ET
26,SPY,361.25,Put,364.0,2022-10-12,1.0,5.18,5.22,5.26,5.08,1118.0,3388.0,"-1,479",35.21%,12:12 ET
96,SPY,361.25,Put,363.0,2022-10-12,1.0,4.53,4.55,4.56,4.10,1309.0,3760.0,-196,35.73%,12:14 ET
111,QQQ,266.15,Put,269.0,2022-10-12,1.0,4.83,4.87,4.90,4.92,558.0,996.0,-135,40.34%,12:06 ET
138,QQQ,266.15,Put,280.0,2022-10-12,1.0,15.18,15.23,15.28,14.26,1311.0,2107.0,-52,59.90%,12:00 ET
162,SPY,361.25,Put,366.0,2022-10-12,1.0,6.79,6.85,6.90,6.85,568.0,3709.0,-20,36.56%,12:08 ET
181,SPY,361.25,Call,352.0,2022-10-12,1.0,8.55,8.61,8.66,8.27,749.0,410.0,-1,43.95%,12:06 ET
250,SPY,361.25,Call,354.0,2022-10-12,1.0,6.87,6.92,6.96,7.03,969.0,1164.0,+13,42.21%,12:14 ET
275,IWM,169.10,Put,165.0,2022-10-12,1.0,0.37,0.38,0.38,0.35,3605.0,3445.0,+43,41.36%,12:14 ET
276,IWM,169.10,Call,167.0,2022-10-12,1.0,2.28,2.30,2.31,2.20,2631.0,300.0,+44,46.85%,12:11 ET
284,SPY,361.25,Call,351.0,2022-10-12,1.0,9.46,9.52,9.58,10.01,532.0,651.0,+54,45.64%,11:46 ET
299,IWM,169.10,Call,166.0,2022-10-12,1.0,2.97,3.01,3.04,3.01,910.0,433.0,+68,48.86%,12:12 ET
317,QQQ,266.15,Call,261.0,2022-10-12,1.0,4.74,4.77,4.80,5.45,1862.0,106.0,+86,42.08%,11:56 ET

In [13]:
#Merge data of increase and decrease dataframe

combine_df = increase_min_DTE.merge(decrease_min_DTE, how= 'outer')

In [14]:
combine_df

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,SPY,361.25,Call,365.0,2022-10-12,1.0,0.93,0.94,0.94,1.00,30958.0,14835.0,"+11,238",36.71%,12:15 ET
1,SPY,361.25,Call,362.0,2022-10-12,1.0,1.87,1.88,1.88,1.98,36489.0,13518.0,"+11,238",37.31%,12:15 ET
2,SPY,361.25,Put,350.0,2022-10-12,1.0,0.26,0.27,0.27,0.20,31136.0,22920.0,"+10,889",38.18%,12:14 ET
3,QQQ,266.15,Call,270.0,2022-10-12,1.0,0.57,0.58,0.58,0.58,11832.0,10743.0,"+8,650",40.74%,12:09 ET
4,QQQ,266.15,Put,255.0,2022-10-12,1.0,0.13,0.14,0.14,0.13,5868.0,9051.0,"+7,471",44.56%,12:06 ET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,IWM,169.10,Put,165.0,2022-10-12,1.0,0.37,0.38,0.38,0.35,3605.0,3445.0,+43,41.36%,12:14 ET
83,IWM,169.10,Call,167.0,2022-10-12,1.0,2.28,2.30,2.31,2.20,2631.0,300.0,+44,46.85%,12:11 ET
84,SPY,361.25,Call,351.0,2022-10-12,1.0,9.46,9.52,9.58,10.01,532.0,651.0,+54,45.64%,11:46 ET
85,IWM,169.10,Call,166.0,2022-10-12,1.0,2.97,3.01,3.04,3.01,910.0,433.0,+68,48.86%,12:12 ET
86,QQQ,266.15,Call,261.0,2022-10-12,1.0,4.74,4.77,4.80,5.45,1862.0,106.0,+86,42.08%,11:56 ET

In [15]:
combine_df.dtypes

Symbol       object
Price       float64
Type         object
Strike      float64
Exp Date     object
DTE         float64
Bid         float64
Midpoint    float64
Ask         float64
Last        float64
Volume      float64
Open Int    float64
OI Chg       object
IV           object
Time         object
dtype: object

In [16]:
#Transfer column 'OI Chg'datatype from str to float.
combine_df['OI Chg'] = combine_df['OI Chg'].str.replace(',', '').str.replace('unch', '0').astype(float)
combine_df.dtypes

Symbol       object
Price       float64
Type         object
Strike      float64
Exp Date     object
DTE         float64
Bid         float64
Midpoint    float64
Ask         float64
Last        float64
Volume      float64
Open Int    float64
OI Chg      float64
IV           object
Time         object
dtype: object

In [17]:
#Transfer column 'IV'datatype from str to float.
combine_df['IV'] = combine_df['IV'].str.replace('%', '').astype(float)/100
combine_df.dtypes

Symbol       object
Price       float64
Type         object
Strike      float64
Exp Date     object
DTE         float64
Bid         float64
Midpoint    float64
Ask         float64
Last        float64
Volume      float64
Open Int    float64
OI Chg      float64
IV          float64
Time         object
dtype: object

In [18]:
# Sort by this orders Symbol,Type,Strike,Open Int,Volume,OI Chg,IV

combine_sort_df = combine_df.sort_values(['Symbol','Type','Strike','Open Int','Volume','OI Chg','IV'])

In [19]:
combine_df

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,SPY,361.25,Call,365.0,2022-10-12,1.0,0.93,0.94,0.94,1.00,30958.0,14835.0,11238.0,0.3671,12:15 ET
1,SPY,361.25,Call,362.0,2022-10-12,1.0,1.87,1.88,1.88,1.98,36489.0,13518.0,11238.0,0.3731,12:15 ET
2,SPY,361.25,Put,350.0,2022-10-12,1.0,0.26,0.27,0.27,0.20,31136.0,22920.0,10889.0,0.3818,12:14 ET
3,QQQ,266.15,Call,270.0,2022-10-12,1.0,0.57,0.58,0.58,0.58,11832.0,10743.0,8650.0,0.4074,12:09 ET
4,QQQ,266.15,Put,255.0,2022-10-12,1.0,0.13,0.14,0.14,0.13,5868.0,9051.0,7471.0,0.4456,12:06 ET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,IWM,169.10,Put,165.0,2022-10-12,1.0,0.37,0.38,0.38,0.35,3605.0,3445.0,43.0,0.4136,12:14 ET
83,IWM,169.10,Call,167.0,2022-10-12,1.0,2.28,2.30,2.31,2.20,2631.0,300.0,44.0,0.4685,12:11 ET
84,SPY,361.25,Call,351.0,2022-10-12,1.0,9.46,9.52,9.58,10.01,532.0,651.0,54.0,0.4564,11:46 ET
85,IWM,169.10,Call,166.0,2022-10-12,1.0,2.97,3.01,3.04,3.01,910.0,433.0,68.0,0.4886,12:12 ET
86,QQQ,266.15,Call,261.0,2022-10-12,1.0,4.74,4.77,4.80,5.45,1862.0,106.0,86.0,0.4208,11:56 ET

In [ ]:
# Create the function for clean data acquire.
def get_data(date,types,DTE):

        increase = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Increase/{types}-increase-change-in-open-interest-{date}.csv'))
        decrease = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Decrease/{types}-decrease-change-in-open-interest-{date}.csv'))
        
        #Combine DataFram
        combine_df = increase.merge(decrease, how= 'outer')
        
        #Select the DTE
        if DTE == 'min':
            combine_min_DTE = combine_df[combine_df['DTE'] == increase['DTE'].min()]
        else:
            combine_min_DTE = combine_df[combine_df['DTE'] <= DTE]
            
        combine_min_DTE = combine_min_DTE.dropna()
        
        
        #Transfer column 'OI Chg'datatype from str to float.
        combine_min_DTE['OI Chg'] = combine_min_DTE['OI Chg'].str.replace(',', '').str.replace('unch', '0').astype(float)
        
        #Transfer column 'IV'datatype from str to float.
        combine_min_DTE['IV'] = combine_min_DTE['IV'].str.replace('%', '').str.replace(',', '').astype(float)/100
        
        #Sort data
        combine_sort_df = combine_min_DTE.sort_values(['Symbol','Type','Strike','Open Int','Volume','OI Chg','IV'])
        
        return combine_sort_df

In [ ]:
a = get_data('09-13-2022')

a.head()

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
1448,AAL,13.68,Call,13.5,2022-09-16,3.0,0.41,0.42,0.43,0.42,983.0,3713.0,-124.0,0.6522,2022-09-13
1058,AAL,13.68,Call,14.0,2022-09-16,3.0,0.17,0.18,0.19,0.19,4682.0,19976.0,-1406.0,0.6480,2022-09-13
1631,AAL,13.68,Put,13.0,2022-09-16,3.0,0.09,0.10,0.10,0.10,3197.0,40030.0,-61.0,0.6983,2022-09-13
332,AAL,13.68,Put,13.5,2022-09-16,3.0,0.21,0.22,0.23,0.23,3529.0,3365.0,1213.0,0.6364,2022-09-13
303,AAL,13.68,Put,14.0,2022-09-16,3.0,0.47,0.49,0.50,0.47,9410.0,14360.0,1308.0,0.5660,2022-09-13